# Page settings
baseurl = "/"
title = "AdeptStack"
languageCode = "en-us"
theme = "hugo-elate-theme"

[params]
  
  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = ""
  description = ""
  email = ""
  # Navigation
  [params.navigation]
    brand = "AdeptStack"
    home = "Home"
    work = "Work"
    testimonials = "Testimonials"
    services = "Services"
    about = "About"
    contact = "Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10
  
  # Hero section
  [params.hero]
    title = "BRING NEW PERSPECTIVE"
    subtitle = 'Innovation. Delivered.'
 
  # Work section
  [params.work]
    enable = true
    title = "Work"
    description = ""
    footertext = ''

    [[params.work.row]]
      img = "work_1.jpg"
      alt = "Image2"
      title = "EngageKit"
      subtitle = "Customer Engagement Platform"

  # Contact section
  [params.contact]
    enable = true
    map = true
    title = "Get in touch"
    description = ""
    
    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-envelope", "benjamin.lai@adeptstack.com"],
        ["icon-globe", '<a href="http://adeptstack.com/" target="_blank">adeptstack.com</a>']
      ]

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; AdeptStack. All Rights Reserved.'
